Repository codeit-bootcamp-frontend/6-Sprint-Mission, pull requests merged in 2024-05, with the labels that each got.

#500 [배현지] Sprint6
  src/api.js
  src/assets/arrow-down.png
  src/assets/favorite.png
  src/assets/plus-icon.png
  src/assets/search.png
  src/components/App.module.css
  src/components/BestProductsList.css
  src/components/BestProductsList.js
  src/components/BestProductsListItem.css
  src/components/BestProductsListItem.js
  src/components/FileInput.css
  src/components/FileInput.js
  src/components/Nav.js
  src/components/Nav.module.css
  src/components/ProductRagistrationForm.css
  src/components/ProductRagistrationForm.js
  src/components/ProductsList.css
  src/components/ProductsList.js
  src/components/ProductsListItem.css
  src/components/ProductsListItem.js
  src/components/ToggleMenu.js
  src/components/ToggleMenu.module.css
  src/pages/ProductRagistrationPage.js
  src/pages/UsedMarketPage.css
  src/pages/UsedMarketPage.js
Labels: 미완성🫠

#491 [김유정] Sprint6
  css/reset.css
  css/style.css
  faq.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/big_logo.png
  image/favicon.png
  image/google.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/kakao.png
  image/kyj-pandamarket.png
  image/login.png
  image/logo.png
  image/pw_icon.png
  image/signup.png
  index.html
  items.html
  js/member.js
  login.html
  package-lock.json
  package.json
  privacy.html
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  signup.html
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/images/ic_plus.png
  src/assets/images/logo.png
  src/assets/images/logo_m.png
  src/assets/images/profile.png
  src/components/Header.jsx
  src/components/Market.jsx
  src/components/MarketList.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/mock.json
  src/pages/AddItem/AddItem.jsx
  src/pages/AddItem/FileInput.jsx
  src/pages/HomePage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/AddItemStyled.jsx
  src/styles/Header.css
  src/styles/InnerContainer.jsx
  src/styles/reset.css
Labels: 미완성🫠

#477 [이영훈] sprint 6
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Button.css
  src/components/Button.js
  src/components/FileInput.css
  src/components/FileInput.js
  src/components/Header.css
  src/components/Header.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/UploadProducts.css
  src/components/UploadProducts.js
  src/image/logo.svg
  src/image/panda_logo.svg
  src/image/search_Icon.svg
  src/image/tee_img.png
  src/image/x_button_img.svg
  src/image/아이패드 미니 팝니다.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 미완성🫠

#471 React 이동규 sprint3
  src/App.js
  src/api/api.js
  src/components/BestProduct.js
  src/components/BestProduct.jsx
  src/components/BestProducts.js
  src/components/BestProducts.jsx
  src/components/Button.jsx
  src/components/Comments.jsx
  src/components/Header.js
  src/components/Header.jsx
  src/components/InquiryContainer.jsx
  src/components/InquiryForm.jsx
  src/components/IntroduceContainer.jsx
  src/components/ItemIntroduce.jsx
  src/components/NavigationBar.jsx
  src/components/NavigationBtn.js
  src/components/NoInquire.jsx
  src/components/PageNationBtn.jsx
  src/components/Products.js
  src/components/Products.jsx
  src/components/RegisterForm.js
  src/components/RegisterForm.jsx
  src/components/RegisterItem.js
  src/components/Tag.jsx
  src/components/TotalProduct.jsx
  src/components/TotalProducts.js
  src/components/TotalProducts.jsx
  src/context/LoginContext.js
  src/img/backImage.png
  src/img/mediumHeart.png
  src/img/moreBtn.png
  src/img/noComment.png
  src/img/profileBig.png
  src/img/smallHeart.png
  src/index.js
  src/pages/AddItem.js
  src/pages/Item.js
  src/pages/Items.js
  src/pages/SpecificItem.js
  src/style/BackButton.css
  src/style/Button.css
  src/style/Color.css
  src/style/Comments.css
  src/style/InquiryForm.css
  src/style/NavigationBtn.css
  src/style/NoComment.css
  src/style/RegisterForm.css
  src/style/index.css
  src/style/item.css
Labels: 매운맛🔥

#445 [이소정] sprint5
  assets/css/styles.css
  assets/css/styles.css.map
  assets/css/styles.min.css
  assets/css/styles.min.css.map
  assets/images/common/favicon.ico
  assets/images/common/logo-typo.svg
  assets/images/common/logo.svg
  assets/images/common/og_tag.png
  assets/images/home/Img_home_01.png
  assets/images/home/Img_home_02.png
  assets/images/home/Img_home_03.png
  assets/images/home/Img_home_bottom.png
  assets/images/home/Img_home_top.png
  assets/images/icons/icn-hidden.svg
  assets/images/icons/icn-visible.svg
  assets/images/social/facebook-logo.svg
  assets/images/social/google-logo.png
  assets/images/social/instagram-logo.svg
  assets/images/social/kakao-logo.png
  assets/images/social/twitter-logo.svg
  assets/images/social/youtube-logo.svg
  assets/js/common.js
  assets/scss/abstracts/_mixin.scss
  assets/scss/abstracts/_variables.scss
  assets/scss/base/_preset.scss
  assets/scss/base/_reset.scss
  assets/scss/components/_buttons.scss
  assets/scss/components/_modal.scss
  assets/scss/layout/_footer.scss
  assets/scss/layout/_forms.scss
  assets/scss/layout/_header.scss
  assets/scss/pages/_login.scss
  assets/scss/pages/_main.scss
  assets/scss/styles.scss
  index.html
  login.html
  privacy.html
  public/index.html
  signup.html
  src/api.js
  src/components/App.js
  src/components/ProductList.js
  src/index.js
  test.txt
Labels: 매운맛🔥, 미완성🫠

#488 [이동석] sprint5
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api/api.js
  src/assets/banner-bottom.png
  src/assets/banner-top.png
  src/assets/card1.png
  src/assets/card2.png
  src/assets/card3.png
  src/assets/facebook.png
  src/assets/favicon.ico.png
  src/assets/google.png
  src/assets/ic_arrow_down.svg
  src/assets/ic_heart.svg
  src/assets/ic_search.svg
  src/assets/instagram.png
  src/assets/kakaotalk.png
  src/assets/panda-market-logo.png
  src/assets/twitter.png
  src/assets/visibility_off.svg
  src/assets/visibility_on.svg
  src/assets/youtube.png
  src/components/AllItems.css
  src/components/AllItems.jsx
  src/components/BestItems.css
  src/components/BestItems.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/ItemElement.css
  src/components/ItemElement.jsx
  src/components/styles/global.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#469 [고재성] Sprint5
  panda/src/api/api.js
  panda/src/assets/arrow_right.png
  panda/src/assets/btn_left.png
  panda/src/assets/heart-empty.png
  panda/src/assets/ic_arrow_down.png
  panda/src/assets/ic_search.png
  panda/src/components/AllProducts.jsx
  panda/src/components/App.js
  panda/src/components/BestProducts.jsx
  panda/src/components/Dropdown.jsx
  panda/src/components/Header.jsx
  panda/src/components/ItemCard.jsx
  panda/src/pages/AddItemPage.jsx
  panda/src/pages/MarketPage.jsx
  panda/src/pages/NotFoundPage.jsx
  panda/tailwind.config.js
Labels: 미완성🫠

#486 [최윤석] sprint6
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/Linkbrary.png
  src/assets/arrow_left.png
  src/assets/arrow_right.png
  src/assets/banner-background_bottom.png
  src/assets/banner-background_top.png
  src/assets/btn_visibility_off_24px.png
  src/assets/btn_visibility_on_24px.png
  src/assets/ic_Google.png
  src/assets/ic_Kakaotalk.png
  src/assets/ic_arrow_down.png
  src/assets/ic_facebook.png
  src/assets/ic_heart.png
  src/assets/ic_instagram.png
  src/assets/ic_plus.png
  src/assets/ic_search.png
  src/assets/ic_twitter.png
  src/assets/ic_youtube.png
  src/assets/panda-face.png
  src/assets/panda-face_title.png
  src/assets/section-img_1.png
  src/assets/section-img_2.png
  src/assets/section-img_3.png
  src/components/AllProducts.css
  src/components/AllProducts.js
  src/components/BestProducts.css
  src/components/BestProducts.js
  src/components/Card.css
  src/components/Card.js
  src/components/FileInput.css
  src/components/FileInput.js
  src/components/Header.css
  src/components/Header.js
  src/components/InputTitle.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/AddItem.css
  src/pages/AddItem.js
  src/pages/FreeCommunity.js
  src/pages/HomePage.js
  src/pages/Items.css
  src/pages/Items.js
  src/pages/SignIn.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#493 React 최수형 sprint5
  src/App.jsx
  src/api.js
  src/components/Header.jsx
  src/components/List.jsx
  src/components/ListItems.jsx
  src/components/ListSection.jsx
  src/components/ListTitle.jsx
  src/components/PaginationNav.jsx
  src/css/Header.css
  src/css/Item.css
  src/css/List.css
  src/css/ListItems.css
  src/css/ListSection.css
  src/css/ListTitle.css
  src/css/PaginationNav.css
  src/hooks/useMediaQuery.js
  src/pages/AddItemPage.jsx
  src/pages/Item.jsx
  src/pages/ItemPage.jsx
  src/pages/Main.jsx
  src/pages/MainPage.jsx
Labels: 순한맛🐑

#536 [김보미] Sprint8
  .gitignore
  README.md
  pandamarket/index.html
  pandamarket/package-lock.json
  pandamarket/package.json
  pandamarket/public/index.html
  pandamarket/src/App.js
  pandamarket/src/App.tsx
  pandamarket/src/api/api.js
  pandamarket/src/api/api.ts
  pandamarket/src/components/BestProductList.js
  pandamarket/src/components/BestProductList.tsx
  pandamarket/src/components/CommentNotFound.tsx
  pandamarket/src/components/FileInput.js
  pandamarket/src/components/FileInput.tsx
  pandamarket/src/components/Footer.tsx
  pandamarket/src/components/Header.js
  pandamarket/src/components/Header.tsx
  pandamarket/src/components/Pagination.tsx
  pandamarket/src/components/ProductList.js
  pandamarket/src/components/ProductList.tsx
  pandamarket/src/components/index.tsx
  pandamarket/src/global.d.ts
  pandamarket/src/index.tsx
  pandamarket/src/pages/AddItem.tsx
  pandamarket/src/pages/Items.tsx
  pandamarket/src/pages/ItemsDetail.tsx
  pandamarket/src/pages/Layout.tsx
  pandamarket/src/pages/Main.tsx
  pandamarket/src/pages/Signin.tsx
  pandamarket/src/pages/Signup.tsx
  pandamarket/src/pages/index.js
  pandamarket/src/pages/index.ts
  pandamarket/src/styles/auth.module.css
  pandamarket/src/utils/displayTime.ts
  pandamarket/src/utils/regex.ts
  pandamarket/tsconfig.json
  pandamarket/vite.config.ts
Labels: 순한맛🐑

#526 [장준혁] Sprint8
  package-lock.json
  package.json
  src/App.tsx
  src/api/useFetchComments.ts
  src/api/useFetchItems.ts
  src/components/AllItemsList.tsx
  src/components/CommentInput.tsx
  src/components/CommentList.tsx
  src/components/ItemIntroduction.tsx
  src/components/Navbar.tsx
  src/components/Pagination.tsx
  src/components/ProductForm.tsx
  src/components/RankedItems.tsx
  src/components/SortDropdown.js
  src/components/SortDropdown.tsx
  src/components/index.ts
  src/images/index.ts
  src/index.tsx
  src/pages/AddItem.tsx
  src/pages/Home.tsx
  src/pages/ItemDetails.tsx
  src/pages/Items.tsx
  src/store/paginationStore.ts
  src/store/productCountStore.ts
  src/types/global.d.ts
  src/utils/formatDateDiff.js
  src/utils/formatDateDiff.ts
  src/utils/formatNumber.js
  src/utils/formatNumber.ts
  src/utils/useDeviceSize.ts
  tsconfig.json
Labels: 매운맛🔥

#523 [이재혁] Sprint8
  package-lock.json
  package.json
  public/images/home/closeeyes.png
  public/images/home/openeyes.png
  public/images/home/seach.png
  public/images/social/facebook.png
  public/images/social/google.png
  public/images/social/instagram.png
  public/images/social/kakao.png
  public/images/social/twitter.png
  public/images/social/youtube.png
  public/index.html
  src/App.tsx
  src/api.tsx
  src/components/AddItems.tsx
  src/components/Header.tsx
  src/components/Home.tsx
  src/components/LoginPage.tsx
  src/components/ProductDetail.tsx
  src/components/Products.tsx
  src/components/SignUp.tsx
  src/index.tsx
  src/react-app-env.d.ts
  src/styles/auth.css
  src/styles/global.css
  src/styles/home.css
  tsconfig.json
Labels: 미완성🫠

#531 [김서영] sprint8
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/arrow-down-icon.svg
  src/assets/icons/arrow-left-disabled.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right-disabled.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/arrow-turn.svg
  src/assets/icons/heart-icon.svg
  src/assets/icons/icon-delete-tag-btn.svg
  src/assets/icons/icon-facebook.png
  src/assets/icons/icon-google.svg
  src/assets/icons/icon-instagram.png
  src/assets/icons/icon-kakaotalk.svg
  src/assets/icons/icon-kebab.svg
  src/assets/icons/icon-profile.svg
  src/assets/icons/icon-twitter.png
  src/assets/icons/icon-youtube.png
  src/assets/icons/img-delete-btn.svg
  src/assets/icons/item-search-icon.svg
  src/assets/images/Img-home-bottom.png
  src/assets/images/Img-home-top.png
  src/assets/images/file-input-button.svg
  src/assets/images/main-hot-item.png
  src/assets/images/main-register.png
  src/assets/images/main-search.png
  src/assets/images/panda-logo-text.svg
  src/assets/images/panda-logo.svg
  src/assets/images/panda-text-logo.svg
  src/assets/images/password-eye.svg
  src/components/AddItemPage/AddItemFileInput.tsx
  src/components/AddItemPage/AddItemTagsInput.tsx
  src/components/ItemDetailPage/ItemComments.tsx
  src/components/ItemDetailPage/ItemDetail.tsx
  src/components/ItemListPage/AllItemList.tsx
  src/components/ItemListPage/BestItemList.tsx
  src/components/ItemListPage/Pagination.tsx
  src/components/common/Navbar.tsx
  src/constants/LoginPage/constant.ts
  src/constants/color.ts
  src/custom.d.ts
  src/index.js
  src/index.tsx
  src/pages/AddItemPage.tsx
  src/pages/Home.tsx
  src/pages/ItemDetailPage.tsx
  src/pages/ItemListPage.tsx
  src/pages/LoginPage.tsx
  src/services/api.ts
  src/styles/AddItemFileInput.css
  src/styles/AddItemTagsInput.css
  src/styles/AllItemList.css
  src/styles/LoginPage.css
  src/styles/Pagination.css
  src/types/Item.ts
  src/types/comment.ts
  tsconfig.json
Labels: 매운맛🔥

#530 [신승헌] sprint8
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/api/axios.ts
  src/api/getAllItems.ts
  src/api/getItemCommentsById.ts
  src/api/getItemInfoById.ts
  src/api/getItems.js
  src/components/Layout.css
  src/components/PagiNationBar.css
  src/components/PagiNationBar.jsx
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.tsx
  src/pages/CommunityFeedPage/CommunityFeedPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ItemDetailsPage/ItemDetails.jsx
  src/pages/ItemDetailsPage/ItemDetails.tsx
  src/pages/ItemDetailsPage/ItemDetailsComments.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/MarketPage.tsx
  src/pages/MarketPage/comp/ItemsAllSection.tsx
  src/pages/MarketPage/comp/ItemsBestSection.tsx
  src/pages/MarketPage/comp/MakeItemCard.tsx
  src/pages/MarketPage/comp/MakeItemList.tsx
  src/pages/SignupPage/SignupPage.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/types/Comments.ts
  src/types/Product.ts
  src/types/ProductInfo.ts
  src/types/index.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#547 [장혜민]sprint8
  myts/.gitignore
  myts/README.md
  myts/package-lock.json
  myts/package.json
  myts/public/index.html
  myts/src/App.tsx
  myts/src/api/api.ts
  myts/src/api/axios.ts
  myts/src/asset/logo_face.png
  myts/src/components/Dropdown.jsx
  myts/src/components/FileInput.css
  myts/src/components/FileInput.tsx
  myts/src/components/Header.css
  myts/src/components/Header.tsx
  myts/src/components/ProductForm.css
  myts/src/components/ProductForm.tsx
  myts/src/components/ProductsList.css
  myts/src/components/ProductsList.tsx
  myts/src/components/ReviewList.tsx
  myts/src/index.tsx
  myts/src/pages/AddItemPage.tsx
  myts/src/pages/ItemPage.css
  myts/src/pages/ItemPage.jsx
  myts/src/pages/MarketPage.tsx
  myts/src/react-app-env.d.ts
  myts/src/reportWebVitals.ts
  myts/src/setupTests.ts
  myts/tsconfig.json
  sprint_mission.zip
Labels: 미완성🫠

#532 [한상우] sprint8
  package.json
  src/Api/Axios.ts
  src/Api/SignUpUser.ts
  src/Api/getComments.js
  src/Api/getComments.ts
  src/Api/getProductId.js
  src/Api/getProductId.ts
  src/Api/getProducts.js
  src/Api/getProducts.ts
  src/Api/loginUser.js
  src/Api/loginUser.ts
  src/App.js
  src/components/AddItem.tsx
  src/components/CommentList.tsx
  src/components/FileInputs.tsx
  src/components/InputComment.tsx
  src/components/ProductDetail.tsx
  src/components/Products.tsx
  src/components/SearchProducts.tsx
  src/components/TagInput.tsx
  src/components/form/LoginForm.tsx
  src/components/form/SignUpForm.tsx
  src/components/form/SignUpStyle.ts
  src/components/layouts/Header.tsx
  src/components/layouts/Layouts.tsx
  src/index.d.ts
  src/pages/AddItemPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProductDetailPage.tsx
  src/pages/SignInPage.js
  src/pages/SignInPage.tsx
  src/utils/validation/Message.js
  src/utils/validation/Message.ts
  src/utils/validation/Schema.js
  src/utils/validation/Schema.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, 매운맛🔥

#543 [정민재] sprint8
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/Axios.ts
  src/api/product.api.ts
  src/components/AddItem/AddItemImage.tsx
  src/components/AddItem/AddItemLayout.tsx
  src/components/AddItem/AddTag.tsx
  src/components/AddItem/FileInput.tsx
  src/components/Items/Product/Comment.tsx
  src/components/Items/Product/Comments.jsx
  src/components/Items/Product/Comments.tsx
  src/components/Items/Product/Dropdown.tsx
  src/components/Items/Product/Product.tsx
  src/components/Items/Product/ProductAll.tsx
  src/components/Items/Product/ProductBest.tsx
  src/components/Items/Product/ProductFooter.jsx
  src/components/Items/Product/ProductFooter.tsx
  src/components/Items/Product/ProductList.tsx
  src/components/Items/Product/ProductPagination.tsx
  src/components/Layout.tsx
  src/components/Logo.tsx
  src/components/MediaQuery.js
  src/components/MediaQuery.tsx
  src/components/Navigation/Footer.tsx
  src/components/Navigation/Header.tsx
  src/components/Navigation/NavMain.tsx
  src/declarations.d.ts
  src/index.js
  src/index.tsx
  src/pages/AddItem.tsx
  src/pages/Community.tsx
  src/pages/Home.tsx
  src/pages/Item.tsx
  src/pages/ItemsList.tsx
  src/pages/NotFound.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#538 [이승현] Sprint 8
  .eslintrc.cjs
  package-lock.json
  package.json
  src/app/App.jsx
  src/entities/ItemCard/ui/ItemCard.jsx
  src/main.jsx
  src/router/router.jsx
  src/shared/ui/Container.js
  src/shared/ui/Line.js
  src/shared/util/util.js
  src/shared/util/util.jsx
  src/widgets/ImageList/ui/ImageList.jsx
  src/widgets/ProductCommentsSection/ui/ProductCommentsSection.jsx
  src/widgets/ProductInfoSection/ui/ProductInfoSection.jsx
  tsconfig.json
  tsconfig.node.json
  vite.config.js
  vite.config.ts
Labels: 매운맛🔥, 미완성🫠
