Repository codeit-bootcamp-frontend/6-Sprint-Mission, pull requests merged in 2024-07, with the labels that each got.

#702 [임찬호] sprint5
  .eslintrc.cjs
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/index.html
  src/Api.js
  src/App.js
  src/App.jsx
  src/api/api.js
  src/assets/images/home/bottom-banner-image.png
  src/assets/images/home/feature1-image.png
  src/assets/images/home/feature2-image.png
  src/assets/images/home/feature3-image.png
  src/assets/images/home/hero-image.png
  src/assets/images/icons/eye-invisible.svg
  src/assets/images/icons/eye-visible.svg
  src/assets/images/logo/favicon.ico
  src/assets/images/logo/logo.svg
  src/assets/images/logo/og-image.png
  src/assets/images/social/facebook-logo.svg
  src/assets/images/social/google-logo.png
  src/assets/images/social/instagram-logo.svg
  src/assets/images/social/kakao-logo.png
  src/assets/images/social/twitter-logo.svg
  src/assets/images/social/youtube-logo.svg
  src/components/Community.jsx
  src/components/Faq.jsx
  src/components/Home.jsx
  src/components/Items.js
  src/components/Items.jsx
  src/components/Login.jsx
  src/components/Navbar.js
  src/components/Privacy.jsx
  src/components/ProductList.js
  src/components/Signup.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/icon/arrow_left.png
  src/icon/arrow_right.png
  src/icon/ic_arrow_down.png
  src/icon/ic_heart.png
  src/icon/ic_search.png
  src/icon/ic_sort.png
  src/icon/logo_main.png
  src/icon/logo_title.png
  src/index.js
  src/main.jsx
  src/scripts/auth.js
  src/style/GlobalStyle.css
  src/style/Items.css
  src/style/Navbar.css
  src/style/ProductList.css
  src/styles/Auth.css
  src/styles/Global.css
  src/styles/Home.css
  vite.config.js
Labels: 미완성🫠

#718 [이영훈] sprint7
  api/api.js
  api/products/product.ts
  api/products/productComments.ts
  api/products/products.ts
  components/ArticleComments.module.css
  components/ArticleComments.tsx
  components/ArticleFeedComments.tsx
  components/Articles.tsx
  components/BestArticles.tsx
  components/FileInput.tsx
  components/Item/CommentContainer.tsx
  components/Item/CommentForm.tsx
  components/Item/CommentList.tsx
  components/Item/ProductArticle.tsx
  components/LoginSignupForm.tsx
  components/Nav.module.css
  components/Nav.tsx
  components/Pagination.tsx
  components/UploadArticle.tsx
  components/additemPage/FileInput.tsx
  components/additemPage/Header.tsx
  components/additemPage/UploadProducts.tsx
  components/itemsPage/AllProducts.module.css
  components/itemsPage/AllProducts.tsx
  components/itemsPage/AllProductsHeader.module.css
  components/itemsPage/AllProductsHeader.tsx
  components/itemsPage/BestProducts.module.css
  components/itemsPage/BestProducts.tsx
  components/itemsPage/Dropdown.module.css
  components/itemsPage/Dropdown.tsx
  components/itemsPage/PagiNation.module.css
  components/itemsPage/PagiNation.tsx
  components/itemsPage/ProductCard.module.css
  components/itemsPage/ProductCard.tsx
  global.d.ts
  lib/axios.ts
  next.config.js
  package-lock.json
  package.json
  pages/additem.tsx
  pages/index.tsx
  pages/items/Items.module.css
  pages/items/[productId]/index.tsx
  pages/items/index.tsx
  public/images/ic_panda_no_comment.svg
  public/images/ic_return.svg
  style.css
  styles/global.css
  tailwind.config.js
  tsconfig.json
  types/product.ts
  utils/formatDate.ts
  utils/formatTimeAgo.ts
Labels: enhancement, 매운맛🔥

#542 [최윤석] Sprint7
  src/App.jsx
  src/api.js
  src/assets/detail-back-button.png
  src/assets/detail-comments-null.png
  src/assets/detail-favorite-icon.png
  src/components/AllProducts.css
  src/components/AllProducts.js
  src/components/AllProducts.jsx
  src/components/BestProducts.js
  src/components/BestProducts.jsx
  src/components/Card.css
  src/components/Card.js
  src/components/Card.jsx
  src/components/DetailProductComments.css
  src/components/DetailProductComments.jsx
  src/components/DetailProductView.css
  src/components/DetailProductView.jsx
  src/components/FileInput.jsx
  src/components/Header.jsx
  src/components/InputTitle.jsx
  src/components/Product.jsx
  src/index.jsx
  src/pages/AddItem.jsx
  src/pages/Detail.css
  src/pages/Detail.jsx
  src/pages/FreeCommunity.jsx
  src/pages/HomePage.jsx
  src/pages/Items.css
  src/pages/Items.js
  src/pages/Items.jsx
  src/pages/NotFound.jsx
  src/pages/SignIn.jsx
Labels: 매운맛🔥, 미완성🫠

#736 [이종욱] Sprint12
  api/getProduct.ts
  api/itemApi.js
  components/ItemPage/AllItems.module.scss
  components/ItemPage/AllItems.tsx
  components/ItemPage/BestItems.module.scss
  components/ItemPage/BestItems.tsx
  components/ItemPage/Products.module.scss
  components/ItemPage/Products.tsx
  components/ItemPage/SelectMenu.module.scss
  components/ItemPage/SelectMenu.tsx
  components/Layout/Header.tsx
  lib/sort.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/items/[productId]/index.tsx
  pages/items/[productId]/styles.module.scss
  pages/items/index.tsx
  pages/items/styles.module.scss
  src/hooks/useToggle.ts
  src/hooks/useWindowSize.ts
  styles/normalize.scss
Labels: 매운맛🔥, 미완성🫠

#745 [이송아] sprint11
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/api/itemApi.ts
  src/assets/images/icons/icon_google.svg
  src/assets/images/icons/icon_kakao.svg
  src/components/Layout/Header.tsx
  src/components/UI/DeleteButton.tsx
  src/components/UI/DropdownMenu.tsx
  src/components/UI/Icon.tsx
  src/components/UI/PaginationBar.tsx
  src/components/UI/TagInput.tsx
  src/custom.d.ts
  src/index.css
  src/pages/HomePage/HomePage.tsx
  src/pages/ItemPage/ItemPage.tsx
  src/pages/ItemPage/components/CommentItem.tsx
  src/pages/ItemPage/components/CommentThread.tsx
  src/pages/ItemPage/components/ItemCommentSection.tsx
  src/pages/ItemPage/components/ItemProfileSection.tsx
  src/pages/ItemPage/components/LikeButton.tsx
  src/pages/ItemPage/components/TagDisplay.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MarketPage/components/AllItemsSection.tsx
  src/pages/MarketPage/components/BestItemsSection.tsx
  src/pages/MarketPage/components/ItemCard.tsx
  src/styles/global.css
  src/types/CommentTypes.ts
  src/types/ItemTypes.ts
  src/types/ProductTypes.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: 매운맛🔥, 미완성🫠

#722 React 이동규 sprint5
  .gitignore
  next-env.d.ts
  package-lock.json
  package.json
  src/api/api.ts
  src/api/type.ts
  src/components/BestProduct.tsx
  src/components/BestProducts.tsx
  src/components/BestProductsContainer.tsx
  src/components/Comments.tsx
  src/components/CommentsContainer.tsx
  src/components/Header.tsx
  src/components/Inquiries.tsx
  src/components/ItemIntroduce.tsx
  src/components/NoInquiry.tsx
  src/components/PageNationItem.tsx
  src/components/ProductDetail.tsx
  src/components/ProductsContainer.tsx
  src/components/SearchBar.tsx
  src/components/SpecificItem.tsx
  src/components/SpecificItemContainer.tsx
  src/components/TotalProduct.tsx
  src/components/TotalProductsContainer.tsx
  src/index.tsx
  src/pages/MainPage.tsx
  src/style/BestProduct.css
  src/style/ProductIntroduce.module.css
  src/style/TotalProduct.css
  src/util/getCreatedTime.ts
Labels: 매운맛🔥, 미완성🫠

#738 [이승현] sprint12
  package-lock.json
  package.json
  src/app/store/index.tsx
  src/pages/login/ui/index.tsx
  src/react-app-env.d.ts
  src/router/index.tsx
  src/shared/api/api.ts
  src/shared/api/axios.ts
  src/shared/api/type/index.ts
  src/shared/util/RTR.ts
  src/vite-env.d.ts
  src/widgets/header/ui/header.tsx
  tsconfig.json
  vite.config.ts
Labels: 미완성🫠

#743 [김영운] sprint11
  components/SignupForm.tsx
  package-lock.json
  package.json
  pages/api/axios.tsx
  pages/lib/debounce.tsx
  pages/signin/index.tsx
  pages/signin/styles.module.scss
  pages/signup/index.tsx
  pages/signup/styles.module.scss
  public/icon/google-logo.png
  public/icon/kakao-logo.png
  public/icon/logo-lg.svg
  public/icon/logo-sm.svg
Labels: 미완성🫠

#726 [소혜린] sprint 12
  .prettierrc
  docs/list.md
  package-lock.json
  package.json
  src/api/api.ts
  src/api/axiosInstance.ts
  src/components/Nav.tsx
  src/hooks/usePagination.ts
  src/interceptors/axios.ts
  src/interceptors/axiosInterceptor.ts
  src/pages/AddItem/AddItemPage.tsx
  src/pages/AddItem/FileInput.tsx
  src/pages/AddItem/Styles/AddItemPageStyles.ts
  src/pages/App.tsx
  src/pages/Auth/SignInPage.tsx
  src/pages/FleaMarket/Accordion.tsx
  src/pages/FleaMarket/AllProducts.tsx
  src/pages/FleaMarket/BestProducts.tsx
  src/pages/FleaMarket/FleaMarketPage.tsx
  src/pages/FleaMarket/Pagination.tsx
  src/pages/FleaMarket/ProductDetail/Comments.tsx
  src/pages/FleaMarket/ProductDetail/ProductDetailAccordian.tsx
  src/pages/FleaMarket/ProductDetail/ProductDetailPage.tsx
  src/pages/FleaMarket/ProductDetail/Styles/CommentsStyles.ts
  src/pages/FleaMarket/ProductDetail/Styles/ProductDetailPageStyles.ts
  src/types/auth.ts
  src/utils/constant.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#725 [이영훈] sprint12
  api/api.js
  api/products/productComments.ts
  api/products/products.ts
  components/Item/CommentList.tsx
  components/Item/ProductArticle.tsx
  components/additemPage/FileInput.tsx
  components/additemPage/Header.tsx
  components/additemPage/UploadProducts.tsx
  components/itemsPage/ProductCard.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  public/images/ic_heart.svg
  types/product.ts
Labels: 매운맛🔥

#720 [이정민] sprint12
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(products)/additem/page.tsx
  src/app/(products)/items/[id]/page.tsx
  src/app/(products)/items/page.tsx
  src/app/layout.tsx
  src/components/Button/FavoriteButton.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardImage.tsx
  src/components/Comment/Comment.tsx
  src/components/Comment/CommentActions.tsx
  src/components/Comment/CommentAddForm.tsx
  src/components/Comment/CommentModals.tsx
  src/components/Comment/CommentSection.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/PrimaryDropdown.tsx
  src/components/Item/ItemCard.tsx
  src/components/Item/ItemDetailCard.tsx
  src/components/Layout/Header.tsx
  src/components/PageComponents/addboard/PostDetailSection.tsx
  src/components/PageComponents/items/BestItemList.tsx
  src/components/PageComponents/items/EmptyItem.tsx
  src/components/PageComponents/items/ItemCommentSection.tsx
  src/components/PageComponents/items/ItemComments.tsx
  src/components/PageComponents/items/ItemDetailSection.tsx
  src/components/PageComponents/items/ItemTagList.tsx
  src/components/PageComponents/items/NormalItemList.tsx
  src/constants/common.ts
  src/contexts/AuthProvider.tsx
  src/contexts/ModalsWrapper.tsx
  src/contexts/ReactQueryProvider.tsx
  src/contexts/RecoilRootProviders.tsx
  src/contexts/Wrappers.tsx
  src/hooks/useDropdown.ts
  src/hooks/useFavoriteButton.ts
  src/hooks/useFormData.ts
  src/hooks/useModal.ts
  src/lib/api/api.ts
  src/lib/api/auth.ts
  src/lib/api/comment.ts
  src/lib/api/product.ts
  src/lib/utils/getQueryClient.ts
  src/lib/utils/hydrate.client.tsx
  src/lib/utils/uploadImageAndGetUrl.ts
  src/middleware.ts
  src/recoil/atoms/ModalsAtom.ts
  src/recoil/atoms/PopupsAtom.ts
  src/recoil/atoms/UserAtom.ts
  src/types/User.d.ts
Labels: 매운맛🔥

#733 [이율] Sprint11
  .eslintrc.js
  .prettierrc.js
  components/BoardList.tsx
  components/Header.tsx
  components/Input/EmailInput.tsx
  components/Input/FileInput.tsx
  components/Input/PasswordInput.tsx
  components/Input/TextInput.tsx
  components/ItemCard.tsx
  eslint.config.mjs
  next.config.js
  pages/_app.tsx
  pages/addboard.tsx
  pages/boards/[id].tsx
  pages/index.tsx
  pages/items/[id].tsx
  pages/items/index.tsx
  pages/join.tsx
  pages/signin.tsx
  src/api/api.tsx
  src/contexts/AuthProvider.tsx
  src/img/Img_product_empty-sm.png
  src/img/Img_product_empty.png
  src/img/Img_reply_empty.png
  src/img/ic_heart_on.svg
  src/styles/_form.scss
  src/styles/page/DetailPage.scss
Labels: 매운맛🔥

#721 [장준혁] Sprint12
  prettier.config.js
  src/api/apiClient.ts
  src/api/useFetchComments.ts
  src/api/useFetchItems.ts
  src/components/AllItemsList.tsx
  src/components/CommentInput.tsx
  src/components/CommentList.tsx
  src/components/ItemIntroduction.tsx
  src/components/Navbar.tsx
  src/components/Pagination.tsx
  src/components/ProductForm.tsx
  src/components/SortDropdown.tsx
  src/pages/ItemDetails.tsx
Labels: 매운맛🔥

#739 [장소희] sprint7
  src/App.js
  src/api/api.js
  src/components/Comment.jsx
  src/components/DropdownList.jsx
  src/components/Header.jsx
  src/components/Pagination.jsx
  src/imgs/png/images.png
  src/pages/ItemPage/ItemPage.jsx
  src/pages/MarketPage/components/AllItemSection.jsx
  src/pages/MarketPage/components/BestItemSection.jsx
  src/pages/MarketPage/components/ItemCard.jsx
  src/styles/global.css
Labels: 매운맛🔥, 미완성🫠

#730 [이지현] sprint12
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/api/api.ts
  src/api/auth/reissueToken.ts
  src/api/auth/signIn.ts
  src/api/auth/signUp.ts
  src/api/comment/createProductComment.ts
  src/api/comment/deleteComment.ts
  src/api/comment/updateComment.ts
  src/api/createImage.ts
  src/api/getProductComment.ts
  src/api/product/createProduct.ts
  src/api/product/deleteProduct.ts
  src/api/productApi.ts
  src/components/Auth/FormError/index.tsx
  src/components/Auth/FormError/style.module.css
  src/components/Auth/FormInput/index.tsx
  src/components/Auth/FormInput/style.module.css
  src/components/Auth/FromWrapper/index.tsx
  src/components/Auth/FromWrapper/style.module.css
  src/components/Auth/SwitchPrompt/index.tsx
  src/components/Auth/SwitchPrompt/style.module.css
  src/components/NewButton/index.tsx
  src/components/NewButton/style.module.css
  src/components/NewDropDown/index.tsx
  src/components/NewDropDown/style.module.css
  src/components/TopNavigation/index.tsx
  src/constants/authForm.ts
  src/constants/errorMessage.ts
  src/constants/orderOption.ts
  src/constants/storageKey.ts
  src/contexts/ItemImageContext.tsx
  src/hooks/useIsLogin.ts
  src/index.tsx
  src/normalize.css
  src/pages/AddItemPage/index.tsx
  src/pages/ItemsDetailPage/components/InquiryComment/index.tsx
  src/pages/ItemsDetailPage/components/ProductDetail/index.tsx
  src/pages/ItemsPage/components/AllProductList/ProductControl.tsx
  src/pages/ItemsPage/components/AllProductList/index.tsx
  src/pages/ItemsPage/components/BestProductList/index.tsx
  src/pages/ItemsPage/components/BestProductList/style.css
  src/pages/ItemsPage/components/BestProductList/style.module.css
  src/pages/ItemsPage/index.tsx
  src/pages/ItemsPage/style.module.css
  src/pages/LoginPage/index.tsx
  src/pages/LoginPage/style.module.css
  src/reset.css
  src/router.tsx
  src/types/auth.ts
  src/types/item.ts
  src/types/order.ts
  src/types/product.ts
  style.module.css.d.ts
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#611 [배영준] sprint8(재업로드)
  custom.d.ts
  package-lock.json
  package.json
  src/App.tsx
  src/api/itemApi.tsx
  src/assets/images/icons/img_nonecomment.svg
  src/assets/images/img_nonecomment.png
  src/components/Layout/Header.tsx
  src/components/UI/DeleteButton.tsx
  src/components/UI/DropdownMenu.tsx
  src/components/UI/ImageUpload.tsx
  src/components/UI/InputItem.tsx
  src/components/UI/PaginationBar.tsx
  src/components/UI/TagInput.jsx
  src/components/UI/TagInput.tsx
  src/index.js
  src/index.tsx
  src/pages/AddItemPage/AddItemPage.tsx
  src/pages/CommunityFeedPage/CommunityFeedPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ItemDetailPage/ItemDetailPage.tsx
  src/pages/ItemDetailPage/components/ItemComments.tsx
  src/pages/ItemDetailPage/components/ItemDetailCard.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MarketPage/MarketPage.tsx
  src/pages/MarketPage/components/AllItemsSection.tsx
  src/pages/MarketPage/components/BestItemsSection.tsx
  src/pages/MarketPage/components/ItemCard.tsx
  src/styles/CommonStyles.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.tsx
  src/types/Items.ts
  tsconfig.json
Labels: 매운맛🔥

#724 [신승헌]sprint12
  .vscode/settings.json
  components/Boards/CommentList.tsx
  hooks/useArticleQuery.ts
  hooks/useCommentQuery.ts
  lib/article.ts
  lib/auth.ts
  lib/comment.ts
  lib/image.ts
  lib/product.ts
  lib/queries.ts
  lib/user.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/boards/[id].tsx
  schema/article.ts
  schema/comment.ts
  schema/list.ts
  types/query.ts
  utils/formatTimeAgo.ts
Labels: 미완성🫠
