Repository codeit-bootcamp-frontend/6-Sprint-Mission, pull requests merged in 2024-03, with the labels that each got.

#16 [한상우]Sprint1
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/image5.png
  images/logo.png
  index.html
  style.css
Labels: enhancement, 매운맛🔥

#21 [최윤석] Sprint1
  font/ROKAF Sans Bold.ttf
  font/ROKAF Sans Medium.ttf
  img/banner-background_bottom.png
  img/banner-background_top.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/section-img_1.png
  img/section-img_2.png
  img/section-img_3.png
  img/판다 얼굴.png
  index.html
  page/faq.html
  page/items.html
  page/privacy.html
  page/signin.html
  style.css
  variable.css
Labels: 매운맛🔥

#27 [이정민] Sprint 1
  README.md
  color.css
  component.css
  icon/check.svg
  icon/eye-off.svg
  icon/eye.svg
  icon/facebook.svg
  icon/google-round.svg
  icon/heart-active.svg
  icon/heart.svg
  icon/insta.svg
  icon/kakao-round.svg
  icon/search.svg
  icon/toggle.svg
  icon/twitter.svg
  icon/youtube.svg
  img/main-img-1.svg
  img/main-img-2.svg
  img/main-img-3.svg
  img/panda-1.svg
  img/panda-2.svg
  index.html
  logo/panda-logo-typo.svg
  logo/panda-logo.svg
  reset.css
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#33 [김민재] Sprint1
  [김민재]Sprint1/font/ROKAF Sans Bold.ttf
  [김민재]Sprint1/font/ROKAF Sans Medium.ttf
  [김민재]Sprint1/image/banner-bottom.png
  [김민재]Sprint1/image/banner.png
  [김민재]Sprint1/image/facebook.png
  [김민재]Sprint1/image/instagram.png
  [김민재]Sprint1/image/logo.svg
  [김민재]Sprint1/image/main-first-image.png
  [김민재]Sprint1/image/main-second-image.png
  [김민재]Sprint1/image/main-third-image.png
  [김민재]Sprint1/image/twitter.png
  [김민재]Sprint1/image/youtube.png
  [김민재]Sprint1/index.html
  [김민재]Sprint1/items.html
  [김민재]Sprint1/privacy.html
  [김민재]Sprint1/signin.html
  [김민재]Sprint1/style.css
Labels: 매운맛🔥

#15 [김지윤] Sprint1
  .DS_Store
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  sprint1/.DS_Store
  sprint1/img/.DS_Store
  sprint1/img/banner_bottom.png
  sprint1/img/banner_top.png
  sprint1/img/ic_facebook.png
  sprint1/img/ic_instagram.png
  sprint1/img/ic_twitter.png
  sprint1/img/ic_youtube.png
  sprint1/img/logo.png
  sprint1/img/promotion1.png
  sprint1/img/promotion2.png
  sprint1/img/promotion3.png
  sprint1/index.css
  sprint1/index.html
Labels: 매운맛🔥

#6 [김제완] Sprint1
  panda/faq.html
  panda/img/ic_facebook.svg
  panda/img/ic_instagram.svg
  panda/img/ic_twitter.svg
  panda/img/ic_youtube.svg
  panda/img/img_home_01.svg
  panda/img/img_home_02.svg
  panda/img/img_home_03.svg
  panda/img/img_home_bottom.svg
  panda/img/img_home_top.svg
  panda/img/panda_logo.svg
  panda/img/panda_logo_text.svg
  panda/index.html
  panda/items.html
  panda/login.html
  panda/privacy.html
  panda/style.css
Labels: 매운맛🔥

#1 [이경원] Sprint1
  faq.html
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/img1.png
  img/img2.png
  img/img3.png
  img/img4.png
  img/img5.png
  img/logo.png
  index.html
  index_style.css
  items.html
  login.html
  privacy.html
Labels: 순한맛🐑

#24 [이송아] Sprint1
  .github/pull_request_template.md
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/btn_visibility_off_24px.png
  images/btn_visibility_on_24px.png
  images/favicon.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  images/logo_icon.png
  images/logo_text.png
  index.html
  pages/faq/index.html
  pages/items/index.html
  pages/login/index.html
  pages/privacy/index.html
  styles/common.css
  styles/index.css
  styles/media.css
  styles/reset.css
Labels: 매운맛🔥

#29 [고한샘]sprint 1
  css/index.css
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.svg
  images/ic_instagram.svg
  images/ic_twitter.svg
  images/ic_youtube.svg
  images/logo_home.svg
  index.html
Labels: 순한맛🐑

#36 [김서영] Sprint1
  faq.html
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/logo.png
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 매운맛🔥

#41 [김혜선] Sprint1
  .DS_Store
  custom.css
  image/.DS_Store
  image/btm_banner.png
  image/foot_face.png
  image/foot_insta.png
  image/foot_twitter.png
  image/foot_youtube.png
  image/logo.png
  image/main_banner.png
  image/maincon1.png
  image/maincon2.png
  image/maincon3.png
  index.html
  login.html
  sub/faq.html
  sub/item.html
  sub/policy.html
Labels: 매운맛🔥

#39 [이대양] Sprint1
  mission_1/assets/banner-img.png
  mission_1/assets/facebook.png
  mission_1/assets/footer-banner-img.png
  mission_1/assets/instagram.png
  mission_1/assets/logo.png
  mission_1/assets/section-img-1.png
  mission_1/assets/section-img-2.png
  mission_1/assets/section-img-3.png
  mission_1/assets/twitter.png
  mission_1/assets/youtube.png
  mission_1/faq.html
  mission_1/index.html
  mission_1/items.html
  mission_1/privacy.html
  mission_1/reset.css
  mission_1/signin.html
  mission_1/style.css
Labels: 매운맛🔥

#45 [이소정] Sprint1
  assets/css/common.css
  assets/css/reset.css
  assets/css/style.css
  assets/images/Img_home_01.png
  assets/images/Img_home_02.png
  assets/images/Img_home_03.png
  assets/images/Img_home_bottom.png
  assets/images/Img_home_top.png
  assets/images/logo.svg
  index.html
Labels: 매운맛🔥

#5 [이율] Sprint1
  sprint1/dist/css/style.min.css
  sprint1/dist/img/Img_home_01.png
  sprint1/dist/img/Img_home_02.png
  sprint1/dist/img/Img_home_03.png
  sprint1/dist/img/Img_home_bottom.png
  sprint1/dist/img/Img_home_top.png
  sprint1/dist/img/ic_facebook.svg
  sprint1/dist/img/ic_instagram.svg
  sprint1/dist/img/ic_twitter.svg
  sprint1/dist/img/ic_youtube.svg
  sprint1/dist/img/logo.png
  sprint1/dist/scss/_common.scss
  sprint1/dist/scss/_component.scss
  sprint1/dist/scss/_index.scss
  sprint1/dist/scss/_layout.scss
  sprint1/dist/scss/_reset.scss
  sprint1/dist/scss/style.scss
  sprint1/index.html
Labels: 매운맛🔥

#9 [이은빈] sprint1
  css/style.css
  faq.html
  font/ROKAF Sans Bold.otf
  font/ROKAF Sans Bold.ttf
  font/ROKAF Sans Medium.otf
  font/ROKAF Sans Medium.ttf
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.svg
  img/ic_instagram.svg
  img/ic_twitter.png
  img/ic_youtube.png
  img/main1.png
  img/main2.png
  img/main3.png
  img/판다 얼굴.svg
  index.html
  items.html
  privacy.html
  signin.html
Labels: 매운맛🔥

#18 [채종민]Sprint1
  code/image/Img_home_01.png
  code/image/Img_home_02.png
  code/image/Img_home_03.png
  code/image/Img_home_bottom.png
  code/image/Img_home_top.png
  code/image/Property 1=Variant3.png
  code/image/ic_facebook.png
  code/image/ic_instagram.png
  code/image/ic_twitter.png
  code/image/ic_youtube.png
  code/image/standard=pc.png
  code/index.html
  code/style.css
Labels: 매운맛🔥

#43 [이종욱] sprint1
  .gitignore
  assets/fonts/index.css
  assets/images/fb.svg
  assets/images/instagram.svg
  assets/images/panda1.svg
  assets/images/panda2.svg
  assets/images/panda3.svg
  assets/images/panda4.svg
  assets/images/panda5.svg
  assets/images/panda6.svg
  assets/images/twitter.svg
  assets/images/youtube.svg
  faq/index.html
  index.html
  items/index.html
  privacy/index.html
  scripts/main.js
  signin/index.html
  styles/reset.css
  styles/style.css
Labels: 매운맛🔥

#31 [조현지]sprint1
  README.md
  base.css
  img/Img_home_bottom.png
  img/Img_home_hot-item.png
  img/Img_home_register.png
  img/Img_home_search.png
  img/Img_home_top.png
  img/icon/ic_facebook.svg
  img/icon/ic_instagram.svg
  img/icon/ic_twitter.svg
  img/icon/ic_youtube.svg
  img/logo/img_logo.png
  img/logo/logo.png
  index.html
  main.css
  reset.css
Labels: 매운맛🔥

#32 [유주민] sprint1
  faq.html
  images/home-banner/home-bottom.svg
  images/home-banner/home-top.svg
  images/home-banner/logo.svg
  images/home-container/item.svg
  images/home-container/register.svg
  images/home-container/search.svg
  images/icons/ic_facebook.svg
  images/icons/ic_instagram.svg
  images/icons/ic_panda_face.svg
  images/icons/ic_twitter.svg
  images/icons/ic_youtube.svg
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 매운맛🔥

#37 [이도요] Sprint1
  images/content2.png
  images/content3.png
  images/facebook.png
  images/insta.png
  images/login.png
  images/logo.png
  images/panda.png
  images/panda2.png
  images/x.png
  images/youtube.png
  index.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#55 [안상균] sprint1
  README.md
  global.css
  images/banner1.png
  images/banner2.png
  images/bear.svg
  images/clothes.jpg
  images/facebook.png
  images/instagram.png
  images/register.jpg
  images/search.jpg
  images/twitter.png
  images/youtube.png
  import.css
  index.html
  landing1.css
Labels: 매운맛🔥, 미완성🫠

#26 스프린트 미션1
  .github/.gitignore
  ROKAF Sans Bold.ttf
  facebook.png
  hotitem.png
  index.html
  insta.png
  panda.png
  panda_logo.png
  panda_twin.png
  register.png
  search.png
  stylesheet1.css
  twitter.png
  youtube.png
Labels: 매운맛🔥, 미완성🫠

#50 [고재성] Sprint1
  .DS_Store
  css/base.css
  css/main.css
  css/reset.css
  faq.html
  images/.DS_Store
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  items.html
  login.html
  privacy.html
Labels: 매운맛🔥

#30 [송현정] sprint1
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/Property 1=Default.png
  img/Property 1=Heart.png
  img/Property 1=Typo.png
  img/Property 1=Variant2.png
  img/Property 1=active.png
  img/icon/Frame 2609150.png
  img/icon/Frame 2609260.png
  img/icon/ic_facebook.png
  img/icon/ic_facebook.svg
  img/icon/ic_instagram.png
  img/icon/ic_instagram.svg
  img/icon/ic_twitter.png
  img/icon/ic_twitter.svg
  img/icon/ic_youtube.png
  img/icon/ic_youtube.svg
  img/logo.png
  img/signature.png
  index.html
  reset.css
  style.css
Labels: 매운맛🔥, 미완성🫠

#7 [최수형] Sprint 1
  README.md
  css/index.css
  css/reset.css
  css/style.css
  images/ico_facebook.svg
  images/ico_insta.svg
  images/ico_twitter.svg
  images/ico_youtube.svg
  images/item_01.svg
  images/item_02.svg
  images/item_03.svg
  images/logo.svg
  images/panda_bottom.svg
  images/panda_top.svg
  images/thumbnail.jpg
  index.html
  pages/faq.html
  pages/items.html
  pages/privacy.html
  pages/signin.html
Labels: 순한맛🐑

#20 [이동규]sprint-1
  .github/pull_request_template.md
  mission1/icon/facebook.png
  mission1/icon/instagram.png
  mission1/icon/twitter.png
  mission1/icon/youtube.png
  mission1/img/bottomImage.png
  mission1/img/hotIem.png
  mission1/img/registerImage.png
  mission1/img/schoolPanda.png
  mission1/img/search.png
  mission1/index.html
  mission1/item/item.html
  mission1/login/login.html
  mission1/logo/pandaMarket.png
  mission1/style.css
Labels: 매운맛🔥

#2 [천권희] Sprint1
  assets/img/Img_home_01.png
  assets/img/Img_home_02-1.png
  assets/img/Img_home_03.png
  assets/img/Img_home_bottom.png
  assets/img/Img_home_top.png
  assets/logo/ic_facebook.svg
  assets/logo/ic_instagram.svg
  assets/logo/ic_twitter.svg
  assets/logo/ic_youtube.svg
  assets/logo/logo.svg
  docs/기능 목록.md
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  styles/main.css
  styles/reset.css
  styles/variables.css
Labels: 매운맛🔥

#3 [류혜원] Sprint1
  .gitignore
  README.md
  faq/index.html
  images/.DS_Store
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  styles/global.css
  styles/home.css
  styles/reset.css
Labels: 매운맛🔥

#13 [이지현] Sprint1
  assets/icons/facebook.svg
  assets/icons/instagram.svg
  assets/icons/twitter.svg
  assets/icons/youtube.svg
  assets/images/home-bottom.png
  assets/images/home-main-1.png
  assets/images/home-main-2.png
  assets/images/home-main-3.png
  assets/images/home-top.png
  assets/logos/icon-logo.png
  assets/logos/panda-logo.png
  faq/index.html
  global.css
  index.html
  items/index.html
  login/index.html
  normalize.css
  privacy/index.html
  style.css
Labels: 매운맛🔥

#52 [이승현] Sprint1
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/mainLogo.jpg
  image/판다마켓.jpg
  index.html
  style.css
Labels: 매운맛🔥

#10 [장준혁] Sprint1
  images/bottom_img.png
  images/header_img.png
  images/homeimg_1.png
  images/homeimg_2.png
  images/homeimg_3.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  pages/faq/index.html
  pages/items/index.html
  pages/privacy/index.html
  pages/signin/index.html
  styles/style.css
Labels: 매운맛🔥

#56 [박지민]sprint1
  sprint_mission/Img_home_01.png
  sprint_mission/Img_home_02.png
  sprint_mission/Img_home_03.png
  sprint_mission/Img_home_bottom.png
  sprint_mission/Img_home_top.png
  sprint_mission/Property 1=Variant3.png
  sprint_mission/ic_facebook.png
  sprint_mission/ic_instagram.png
  sprint_mission/ic_twitter.png
  sprint_mission/ic_youtube.png
  sprint_mission/index.html
  sprint_mission/status=Default (1).png
  sprint_mission/status=Default.png
  sprint_mission/style.css
Labels: 미완성🫠, 순한맛🐑

#59 [장혜민]스프린트미션1
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/logo_face.png
  index.html
  items.html
  login.html
  style.css
Labels: 미완성🫠

#34 [정지현] sprint1
  facebook.html
  faq.html
  images/button.png
  images/home_01.png
  images/home_02.png
  images/home_03.png
  images/home_bottom.png
  images/home_top.png
  images/ic_facebook.svg
  images/ic_instagram.svg
  images/ic_twitter.svg
  images/ic_youtube.svg
  images/login.png
  images/logo.png
  index.html
  instagram.html
  items.html
  privacy.html
  signin.html
  style.css
  twitter.html
  youtube.html
Labels: 미완성🫠, 순한맛🐑

#42 [임진조] Sprint1
  pandamarket/images/Img_home_01.png
  pandamarket/images/Img_home_02.png
  pandamarket/images/Img_home_03.png
  pandamarket/images/Img_home_bottom.png
  pandamarket/images/Img_home_top.png
  pandamarket/images/ic_facebook.png
  pandamarket/images/ic_instagram.png
  pandamarket/images/ic_twitter.png
  pandamarket/images/ic_youtube.png
  pandamarket/images/logo.png
  pandamarket/index.html
  pandamarket/style.css
Labels: 매운맛🔥

#47 [강은우] Sprint1
  faq.html
  image/Img_home_01.png
  image/Img_home_02-1.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Property 1=Typo.png
  image/Property 1=Variant3.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#25 첫번째 스프린트 미션
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/home_logo.png
  images/ic_facebook.svg
  images/ic_instagram.svg
  images/ic_twitter.svg
  images/ic_youtube.svg
  index.html
  style.css
Labels: 매운맛🔥

#8 [최건] Sprint1
  assets/icons/ic_facebook.svg
  assets/icons/ic_instagram.svg
  assets/icons/ic_twitter.svg
  assets/icons/ic_youtube.svg
  assets/icons/icon.svg
  assets/images/img_home_01.png
  assets/images/img_home_02.png
  assets/images/img_home_03.png
  assets/images/img_home_bottom.png
  assets/images/img_home_top.png
  index.css
  index.html
Labels: 매운맛🔥

#14 [소혜린] sprint 1
  images/Icon_facebook.png
  images/Icon_instagram.png
  images/Icon_twitter.png
  images/Icon_youtube.png
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Img_logo.png
  index.html
  style.css
Labels: 매운맛🔥

#35 [배영준] Sprint 1
  faq.html
  img/Property 1=Default.png
  img/Property 1=Variant2.png
  img/img_footer_1.png
  img/img_header_1.png
  img/img_main_1.png
  img/img_main_2.png
  img/img_main_3.png
  img/img_pandalogo_1.png
  img/img_pandalogo_2.png
  img/social/ic_facebook.png
  img/social/ic_instagram.png
  img/social/ic_twitter.png
  img/social/ic_youtube.png
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 매운맛🔥

#23 [정민재] Sprint1
  .github/pull_request_template.md
  faq/index.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/banner_bottom.png
  images/banner_top.png
  images/logo.png
  images/panda.JPG
  images/social/ic_facebook.png
  images/social/ic_instagram.png
  images/social/ic_twitter.png
  images/social/ic_youtube.png
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  style.css
Labels: 매운맛🔥

#46 [김승래] Sprint1
  .github/pull_request_template.md
  mission_1/faq.html
  mission_1/images/Img_home_01.png
  mission_1/images/Img_home_02.png
  mission_1/images/Img_home_03.png
  mission_1/images/Img_home_bottom.png
  mission_1/images/Img_home_top.png
  mission_1/images/ic_facebook.png
  mission_1/images/ic_instagram.png
  mission_1/images/ic_twitter.png
  mission_1/images/ic_youtube.png
  mission_1/images/logo.png
  mission_1/index.html
  mission_1/items.html
  mission_1/privacy.html
  mission_1/signin.html
  mission_1/style.css
Labels: 매운맛🔥

#65 [김용인] Sprint1
  Sprint1/css/index.css
  Sprint1/faq.html
  Sprint1/imgs/Frame 2608833.png
  Sprint1/imgs/Group 19.png
  Sprint1/imgs/Img_home_02.png
  Sprint1/imgs/Img_home_03.png
  Sprint1/imgs/Img_home_bottom.png
  Sprint1/imgs/Img_home_top.png
  Sprint1/imgs/face.png
  Sprint1/imgs/favicon.png
  Sprint1/imgs/insta.png
  Sprint1/imgs/twit.png
  Sprint1/imgs/youtube.png
  Sprint1/index.html
  Sprint1/items.html
  Sprint1/privacy.html
  Sprint1/signin.html
Labels: 매운맛🔥

#61 [함예진] Sprint1
  faq.html
  images/bottom-banner-image.png
  images/facebook-logo.svg
  images/favicon.ico
  images/feature1-image.png
  images/feature2-image.png
  images/feature3-image.png
  images/hero-image.png
  images/instagram-logo.svg
  images/panda-market-logo.png
  images/twitter-logo.svg
  images/youtube-logo.svg
  index.html
  items.html
  privacy.html
  sigin.html
  styles.css
Labels: 미완성🫠

#68 sprint mission1
  faq.html
  images/Hot-item.png
  images/Register.png
  images/SNS-image.png
  images/Search.png
  images/bottom-panda-image.png
  images/panda-market-logo.png
  images/top-panda-image.png
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 순한맛🐑

#74 [장익재]sprint1
  .DS_Store
  img/.DS_Store
  img/home/bottom-banner-image.png
  img/home/feature1-image.png
  img/home/feature2-image.png
  img/home/feature3-image.png
  img/home/hero-image.png
  img/logo/favicon.ico
  img/logo/panda-market-logo.png
  img/social/facebook-logo.svg
  img/social/instagram-logo.svg
  img/social/twitter-logo.svg
  img/social/youtube-logo.svg
  index.html
  style.css
Labels: 미완성🫠

#71 [김유정] Sprint1
  css/style.css
  faq.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/kyj-pandamarket.png
  image/logo.png
  index.html
  items.html
  login.html
  privacy.html
  test.txt
Labels: 매운맛🔥

#98 [문주영] Sprint1
  .DS_Store
  .vscode/settings.json
  faq.html
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/Img_home_top@2x.png
  images/Img_home_top@3x.png
  images/Property 1=Variant3.png
  images/facebook.png
  images/instagram.png
  images/twitter.png
  images/youtube.png
  index.html
  items.html
  privacy.html
  signin.html
  style.css
Labels: 매운맛🔥

#66 [김보미] Sprint2
  README.md
  img/icon_facebook.png
  img/icon_google.png
  img/icon_insta.png
  img/icon_kakao.png
  img/icon_twitter.png
  img/icon_visibility.png
  img/icon_visibility2.png
  img/icon_youtube.png
  img/img_home_01.png
  img/img_home_02.png
  img/img_home_03.png
  img/img_home_bottom.png
  img/img_home_top.png
  img/logo.png
  img/logo_text.png
  pages/faq.html
  pages/index.html
  pages/items.html
  pages/privacy.html
  pages/signin.html
  pages/signup.html
  style/auth.css
  style/main.css
  style/style.css
Labels: 순한맛🐑

#69 [정우기] Spint2
  README.md
  index.html
  login.html
  login/assets/google-logo.png
  login/assets/kakao-logo.png
  login/assets/logo.png
  login/assets/show-pw.png
  login/style.css
  reset.css
  signup.html
  signup/assets/show-pw.png
  signup/style.css
  style.css
Labels: 매운맛🔥

#82 [최윤석] Sprint2
  img/btn_visibility_off_24px.png
  img/btn_visibility_on_24px.png
  img/ic_Google.png
  img/ic_Kakaotalk.png
  img/panda-face.png
  img/panda-face_title.png
  index.html
  page/signin.html
  page/signup.html
  style/main.css
  style/reset.css
  style/signin.css
  style/signup.css
  style/variable.css
Labels: 매운맛🔥

#123 [한상우] sprint2
  .vscode/settings.json
  LogIn.html
  SignUp.html
  images/favicon.ico
  images/google.png
  images/kakao.png
  index.html
  loginStyle.css
  style.css
Labels: enhancement, 매운맛🔥

#91 [채종민] sprint2
  code/image/main_image/Img_home_01.png
  code/image/main_image/Img_home_02.png
  code/image/main_image/Img_home_03.png
  code/image/main_image/Img_home_bottom.png
  code/image/main_image/Img_home_top.png
  code/image/main_image/ic_facebook.png
  code/image/main_image/ic_instagram.png
  code/image/main_image/ic_twitter.png
  code/image/main_image/ic_youtube.png
  code/image/main_image/logo.png
  code/image/signin_image/Google_Icon.png
  code/image/signin_image/eye_Icon.png
  code/image/signin_image/kakao_Icon.png
  code/image/signin_image/logo.png
  code/image/standard=pc.png
  code/pages/index.html
  code/pages/signin.html
  code/pages/signup.html
  code/stye.css/main.css
  code/stye.css/signin.css
Labels: 매운맛🔥

#102 [이율] Sprint2
  pandaMarket/dist/css/style.min.css
  pandaMarket/dist/img/Img_home_01.png
  pandaMarket/dist/img/Img_home_02.png
  pandaMarket/dist/img/Img_home_03.png
  pandaMarket/dist/img/Img_home_bottom.png
  pandaMarket/dist/img/Img_home_top.png
  pandaMarket/dist/img/ic_facebook.svg
  pandaMarket/dist/img/ic_google.svg
  pandaMarket/dist/img/ic_instagram.svg
  pandaMarket/dist/img/ic_kakao.svg
  pandaMarket/dist/img/ic_twitter.svg
  pandaMarket/dist/img/ic_visibility.svg
  pandaMarket/dist/img/ic_youtube.svg
  pandaMarket/dist/img/logo-big.png
  pandaMarket/dist/img/logo.png
  pandaMarket/dist/img/spr.sprite.png
  pandaMarket/dist/img/spr/visibility-off.png
  pandaMarket/dist/img/spr/visibility-on.png
  pandaMarket/dist/scss/_common.scss
  pandaMarket/dist/scss/_component.scss
  pandaMarket/dist/scss/_form.scss
  pandaMarket/dist/scss/_index.scss
  pandaMarket/dist/scss/_layout.scss
  pandaMarket/dist/scss/_reset.scss
  pandaMarket/dist/scss/_spr.scss
  pandaMarket/dist/scss/_spr.sprite.scss
  pandaMarket/dist/scss/spr.sprite
  pandaMarket/dist/scss/style.scss
  pandaMarket/index.html
  pandaMarket/join.html
  pandaMarket/signin.html
  sprint1/dist/css/style.min.css
  sprint1/dist/scss/_common.scss
  sprint1/dist/scss/_component.scss
  sprint1/dist/scss/_reset.scss
Labels: 매운맛🔥

#63 [김지윤] Sprint2
  .DS_Store
  .gitignore
  images/home/banner-bottom.png
  images/home/banner-top.png
  images/home/promotion-hotitem.png
  images/home/promotion-register.png
  images/home/promotion-search.png
  images/icon/eye-invisible.svg
  images/icon/eye-visible.svg
  images/logo/favicon.ico
  images/logo/logo.png
  images/logo/logo.svg
  images/social/logo-facebook.png
  images/social/logo-google.png
  images/social/logo-instagram.png
  images/social/logo-kakao.png
  images/social/logo-twitter.png
  images/social/logo-youtube.png
  index.html
  signin.html
  signup.html
  sprint1/.DS_Store
  sprint1/img/.DS_Store
  sprint1/index.css
  sprint1/index.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#114 [이은빈] sprint2
  css/reset.css
  css/style.css
  img/google_login.svg
  img/kakao_login.svg
  img/visibility_off.png
  index.html
  login.html
  signin.html
  signup.html
Labels: 매운맛🔥

#85 [이송아] sprint2
  images/btn-visibility-off.svg
  images/btn-visibility-on.svg
  images/btn_visibility_off_24px.png
  images/btn_visibility_on_24px.png
  images/header-logo.svg
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/icon-facebook.svg
  images/icon-google.svg
  images/icon-instagram.svg
  images/icon-kakaotalk.svg
  images/icon-logo.svg
  images/icon-twitter.svg
  images/icon-youtube.svg
  images/img-home-01.png
  images/img-home-02.png
  images/img-home-03.png
  images/img-home-bottom.png
  images/img-home-top.png
  images/logo-big.svg
  images/logo.png
  images/logo_icon.png
  images/logo_text.png
  images/text-logo.svg
  index.html
  js/include.js
  layout/footer.html
  layout/header.html
  pages/faq/index.html
  pages/items/index.html
  pages/login/index.html
  pages/privacy/index.html
  pages/signup/index.html
  pages/src/join.css
  styles/common.css
  styles/global.css
  styles/index.css
  styles/reset.css
Labels: 매운맛🔥

#72 [오채연] Sprint1
  part1/faq.html
  part1/img_index/Img_home_01.png
  part1/img_index/Img_home_02.png
  part1/img_index/Img_home_03.png
  part1/img_index/Img_home_bottom.png
  part1/img_index/Img_home_top.png
  part1/img_index/ic_facebook.png
  part1/img_index/ic_instagram.png
  part1/img_index/ic_twitter.png
  part1/img_index/ic_youtube.png
  part1/img_index/img_logo.png
  part1/img_index/판다 얼굴.png
  part1/index.html
  part1/items.html
  part1/privacy.html
  part1/signin.html
  part1/style.css
Labels: 매운맛🔥

#75 [이경원] sprint2
  CSS/index_style.css
  CSS/signin-style.css
  CSS/signup-style.css
  README.md
  images/bottom-banner-img.png
  images/eyeoff.svg
  images/eyeon.svg
  images/logo.svg
  images/section1.png
  images/section2.png
  images/section3.png
  images/social/facebook-logo.svg
  images/social/google-logo.svg
  images/social/instagram-logo.svg
  images/social/kakao-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  images/top-banner-img.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/logo.png
  index.html
  login.html
  signin.html
  signup.html
Labels: 순한맛🐑

#95 [고한샘] Sprint2
  css/index.css
  css/login.css
  images/favicon.ico
  images/google_logo.svg
  images/kakao_logo.svg
  images/mark_unvisible.svg
  images/mark_visible.svg
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#100 [유성진] Sprint2
  6-Sprint-Mission1/faq.html
  6-Sprint-Mission1/images/Hot-item.png
  6-Sprint-Mission1/images/Register.png
  6-Sprint-Mission1/images/SNS-image.png
  6-Sprint-Mission1/images/Search.png
  6-Sprint-Mission1/images/bottom-panda-image.png
  6-Sprint-Mission1/images/panda-market-logo.png
  6-Sprint-Mission1/images/top-panda-image.png
  6-Sprint-Mission1/index.html
  6-Sprint-Mission1/items.html
  6-Sprint-Mission1/privacy.html
  6-Sprint-Mission1/style.css
  6-Sprint-Mission2/images/icon/eyes.png
  6-Sprint-Mission2/images/icon/google-img.png
  6-Sprint-Mission2/images/icon/kakao-img.png
  6-Sprint-Mission2/images/panda-logo.png
  6-Sprint-Mission2/login.css
  6-Sprint-Mission2/login.html
  6-Sprint-Mission2/signup.css
  6-Sprint-Mission2/signup.html
Labels: 매운맛🔥

#88 [이정민] Sprint2
  assets/icon/check.svg
  assets/icon/eye-off.svg
  assets/icon/eye.svg
  assets/icon/facebook.svg
  assets/icon/google-round.svg
  assets/icon/heart-active.svg
  assets/icon/heart.svg
  assets/icon/insta.svg
  assets/icon/kakao-round.svg
  assets/icon/search.svg
  assets/icon/toggle.svg
  assets/icon/twitter.svg
  assets/icon/youtube.svg
  assets/img/main-img-1.svg
  assets/img/main-img-2.svg
  assets/img/main-img-3.svg
  assets/img/panda-1.svg
  assets/img/panda-2.svg
  assets/img/panda-logo-typo.svg
  assets/img/panda-logo.svg
  index.html
  public/stylesheets/common.css
  public/stylesheets/component.css
  public/stylesheets/reset.css
  public/stylesheets/sign.css
  public/stylesheets/style.css
  signin.html
  signup.html
Labels: 매운맛🔥

#142 [최윤석] Sprint2 코드 리뷰 수정
  page/signin.html
  page/signup.html
  style/signin.css
  style/signup.css
Labels: 매운맛🔥

#73 [송현정] sprint2
  assets/images/Img_home_01.png
  assets/images/Img_home_02.png
  assets/images/Img_home_03.png
  assets/images/Img_home_bottom.png
  assets/images/Img_home_top.png
  assets/images/Property 1=Default.png
  assets/images/Property 1=Heart.png
  assets/images/Property 1=Typo.png
  assets/images/Property 1=Variant2.png
  assets/images/Property 1=active.png
  assets/images/icon/Frame 2609150.png
  assets/images/icon/Frame 2609260.png
  assets/images/icon/btn_visibility_off.png
  assets/images/icon/btn_visibility_on.png
  assets/images/icon/google.png
  assets/images/icon/ic_facebook.png
  assets/images/icon/ic_facebook.svg
  assets/images/icon/ic_instagram.png
  assets/images/icon/ic_instagram.svg
  assets/images/icon/ic_twitter.png
  assets/images/icon/ic_twitter.svg
  assets/images/icon/ic_youtube.png
  assets/images/icon/ic_youtube.svg
  assets/images/icon/kakao.png
  assets/images/logo.png
  assets/images/signature.png
  css/common/common.css
  css/common/reset.css
  css/style.css
  css/user-form.css
  fnq.html
  index.html
  items.html
  js/userForm.js
  login.html
  privacy.html
  reset.css
  signup.html
Labels: 매운맛🔥

#84 [오영택] sprint2
  faq.html
  global.css
  home.css
  home.html
  img/btn_visibility_off.svg
  img/btn_visibility_on.svg
  img/favicon.ico
  img/ic_facebook.svg
  img/ic_google.svg
  img/ic_instagram.svg
  img/ic_kakao.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/img_home_01.png
  img/img_home_02.png
  img/img_home_03.png
  img/img_home_bottom.png
  img/img_home_top.png
  img/logo.png
  img/panda-market-logo.png
  items.html
  privacy.html
  signin.css
  signin.html
  signup.css
  singup.html
Labels: 매운맛🔥

#81 [조현지] sprint2
  .vscode/settings.json
  README.md
  assets/fonts/font.css
  assets/img/home_imgs/Img_home_bottom.svg
  assets/img/home_imgs/Img_home_hot_item.png
  assets/img/home_imgs/Img_home_register.png
  assets/img/home_imgs/Img_home_search.png
  assets/img/home_imgs/Img_home_top.svg
  assets/img/icon/google_icon.svg
  assets/img/icon/ic_facebook.svg
  assets/img/icon/ic_instagram.svg
  assets/img/icon/ic_twitter.svg
  assets/img/icon/ic_youtube.svg
  assets/img/icon/kakao_icon.svg
  assets/img/icon/pw_Property=Default.svg
  assets/img/icon/pw_Property=Variant2.svg
  assets/img/logo/img_logo.svg
  assets/img/logo/img_logo_big.png
  assets/img/logo/logo.png
  home.css
  img/Img_home_bottom.png
  img/Img_home_hot-item.png
  img/Img_home_register.png
  img/Img_home_search.png
  img/Img_home_top.png
  img/logo/img_logo.png
  index.html
  main.css
  signin/index.html
  signin/main.js
  signin/signin.css
  signup/index.html
  signup/signup.css
  styles/base.css
  styles/reset.css
Labels: 매운맛🔥

#129 [임찬호] sprint2
  css/sign.css
  css/styles.css
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_instagram.png
  img/ic_kakao.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/invisible.png
  img/logo.png
  img/logo@3x.png
  img/visible.png
  index.html
  js/login.js
  login.html
  signup.html
Labels: 매운맛🔥

#133 [이도요] sprint 2
  images/content2.png
  images/content3.png
  images/facebook.png
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/insta.png
  images/login.png
  images/logo.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/logo/password.png
  images/panda.png
  images/panda2.png
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakaotalk-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  images/x.png
  images/youtube.png
  index.html
  login.html
  signup.html
  style.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥, 미완성🫠

#108 [안상균] sprint2
  faq.html
  global.css
  images/banner1.png
  images/banner2.png
  images/bear.svg
  images/clothes.jpg
  images/etc/btn_visibility.png
  images/etc/google1x.png
  images/etc/google2x.png
  images/etc/google3x.png
  images/etc/kakao1x.png
  images/etc/kakao2x.png
  images/etc/kakao3x.png
  images/etc/스프린트 미션 (Copy).zip
  images/facebook.png
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/instagram.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/register.jpg
  images/search.jpg
  images/social/facebook-logo.svg
  images/social/google1x.png
  images/social/google2x.png
  images/social/google3x.png
  images/social/instagram-logo.svg
  images/social/kakao1x.png
  images/social/kakao2x.png
  images/social/kakao3x.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  images/twitter.png
  images/youtube.png
  import.css
  index.html
  items.html
  landing1.css
  privacy.html
  signin.html
  signup.html
  styles/global.css
  styles/home.css
  styles/sign.css
Labels: 매운맛🔥

#101 [박진경] Sprint2
  banner-bg.png
  banner_button.png
  banner_description.png
  banner_panda.png
  bottom_banner.png
  description1.png
  description2.png
  description3.png
  facebook.png
  google.png
  image1.png
  image2.png
  image3.png
  index.html
  instagram.png
  kakao.png
  login.png
  logo.png
  panda_logo.png
  signin.html
  signin_style.css
  signup.html
  signup_style.css
  style.css
  twitter.png
  visibility_off.png
  youtube.png
Labels: 미완성🫠, 순한맛🐑

#83 [최건] Sprint2
  assets/icons/facebook.svg
  assets/icons/google.svg
  assets/icons/instagram.svg
  assets/icons/invisible.svg
  assets/icons/kakaotalk.svg
  assets/icons/twitter.svg
  assets/icons/visible.svg
  assets/icons/youtube.svg
  core.css
  index.css
  index.html
  pages/login/index.css
  pages/login/index.html
  pages/login/index.js
  pages/signup/index.css
  pages/signup/index.html
  pages/signup/index.js
Labels: 매운맛🔥

#103 [소혜린] sprint 2
  global.css
  images/Icon_google.png
  images/Icon_kakaotalk.png
  images/Img_logo.png
  images/visible.svg
  index.html
  pages/auth/auth.css
  pages/auth/signin/signin.html
  pages/auth/signin/signin.js
  pages/auth/signup/signup.html
  pages/auth/signup/signup.js
  style.css
Labels: 매운맛🔥

#130 [김영운] sprint1 (미션 마무리)
  sprint1/sprint1_main.html
  sprint1/styles/style.css
Labels: 순한맛🐑

#137 [임희서] Sprint2
  assets/icons/ic_facebook.png
  assets/icons/ic_google.png
  assets/icons/ic_instagram.png
  assets/icons/ic_invisible.png
  assets/icons/ic_kakaotalk.png
  assets/icons/ic_pandamarket.png
  assets/icons/ic_twitter.png
  assets/icons/ic_youtube.png
  assets/images/home_01.png
  assets/images/home_02.png
  assets/images/home_03.png
  assets/images/home_bottom.png
  assets/images/home_top.png
  assets/images/logo-image.png
  css/global.css
  css/login-register-style.css
  css/reset.css
  css/style.css
  html/login.html
  html/register.html
  index.html
Labels: 매운맛🔥

#131 [장소희] sprint1
  .github/pull_request_template.md
  faq/index.html
  faq/style.css
  global.css
  img/icon/ic_facebook.svg
  img/icon/ic_instagram.svg
  img/icon/ic_twitter.svg
  img/icon/ic_youtube.svg
  img/icon/판다 얼굴.svg
  img/png/Img_home_01.png
  img/png/Img_home_02.png
  img/png/Img_home_03.png
  img/png/Img_home_bottom.png
  img/png/Img_home_top.png
  img/png/Property 1=Variant3.png
  index.html
  items/index.html
  items/style.css
  privacy/index.html
  privacy/style.css
  signin/index.html
  signin/style.css
  style.css
Labels: 매운맛🔥, 미완성🫠

#90 [이대양] Sprint2
  mission_1/assets/google_logo.png
  mission_1/assets/kakaotalk_logo.png
  mission_1/assets/lens_x.png
  mission_1/index.html
  mission_1/pages/faq.html
  mission_1/pages/items.html
  mission_1/pages/privacy.html
  mission_1/pages/signin.html
  mission_1/pages/signup.html
  mission_1/signin.html
  mission_1/styles/common.css
  mission_1/styles/index.css
  mission_1/styles/reset.css
  mission_1/styles/signinAndSignup.css
Labels: 매운맛🔥

#106 [김승래] Sprint2
  mission_1/CSS/sign.css
  mission_1/CSS/style.css
  mission_1/faq.html
  mission_1/images/ic_google.png
  mission_1/images/ic_kakao.png
  mission_1/images/see_pw.png
  mission_1/images/sign_logo.png
  mission_1/index.html
  mission_1/items.html
  mission_1/privacy.html
  mission_1/signin.html
  mission_1/signup.html
Labels: 매운맛🔥

#109 [정민재] Sprint2
  .github/pull_request_template.md
  images/logo.png
  images/psw_eye/Vector@3x.png
  images/psw_eye/eye_close.png
  images/social_signin/google.png
  images/social_signin/kakao.png
  index.html
  pages/faq/index.html
  pages/items/index.html
  pages/privacy/index.html
  pages/signin/index.html
  pages/signup/index.html
  privacy/index.html
  styles/root.css
  styles/sign_style.css
  styles/style.css
Labels: 매운맛🔥

#44 [이승헌] sprint 1
  assets/ic_facebook.svg
  assets/ic_instagram.svg
  assets/ic_twitter.svg
  assets/ic_youtube.svg
  assets/img_home_01.png
  assets/img_home_02.png
  assets/img_home_03.png
  assets/img_home_bottom.png
  assets/img_home_top.png
  assets/logo.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  styles/common.css
  styles/home.css
  styles/reset.css
Labels: 매운맛🔥

#124 [김용인] Sprint2
  Sprint1/css/index.css
  Sprint1/css/login.css
  Sprint1/css/signin.css
  Sprint1/imgs/eyes.png
  Sprint1/imgs/googlelogo.png
  Sprint1/imgs/kakaologo.png
  Sprint1/imgs/logo.png
  Sprint1/index.html
  Sprint1/login.html
  Sprint1/signin.html
Labels: 매운맛🔥

#143 [유예하] sprint2
  CSS/global.css
  CSS/reset.css
  CSS/signin-style.css
  CSS/styles.css
  assets/Frame 2608833.png
  assets/Group 19.png
  assets/Group.png
  assets/Group2.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/Vector1.png
  assets/Vector2.png
  assets/btn_large.png
  assets/btn_small.png
  assets/btn_visibility.png
  assets/google.png
  assets/kakao.png
  assets/logo-signin.png
  assets/logo.png
  assets/판다 얼굴.png
  faq.html
  index.html
  items.html
  privacy.html
  signin.html
  signup.html
Labels: 순한맛🐑

#111 [김주영] Sprint1
  .github/faq.html
  .github/index.html
  .github/items.html
  .github/privacy.html
  .github/signin.html
  .github/style.css
  image/Img_home_01.png
  image/Img_home_02-1.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Property 1=Variant3.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/판다 얼굴.png
Labels: 매운맛🔥

#136 [이재혁] Sprint2
  images/home/favicon.ico
  images/home/검색판다.png
  images/home/눈.png
  images/home/로그인판다.png
  images/home/물건판다.png
  images/home/옷판다.png
  images/home/판다1.png
  images/home/판다2.png
  images/home/판다얼굴.png
  images/social/구글.png
  images/social/유튜브.png
  images/social/인스타그램.png
  images/social/카톡.png
  images/social/트위터.png
  images/social/페이스북.png
  index.html
  log.css
  signin.html
  signup.html
  style.css
  sup.css
  test.txt
  test3.txt
Labels: 매운맛🔥

#151 [곽서연] sprint 2
  eye.png
  google.png
  kakaotalk.png
  login/login.css
  login/login.html
  logo.png
  main/footerPanda.png
  main/header-panda.png
  main/index.html
  main/logo.png
  main/main.css
  main/section1-img.png
  main/section2-img.png
  main/section3-img.png
  signup/signup.css
  signup/signup.html
Labels: 매운맛🔥, 미완성🫠

#122 [임진조] sprint2
  pandamarket/images/close_eye.png
  pandamarket/images/google.png
  pandamarket/images/kakao.png
  pandamarket/images/login_logo.png
  pandamarket/images/open_eye.png
  pandamarket/index.html
  pandamarket/scripts/signin.js
  pandamarket/signin.html
  pandamarket/signup.html
  pandamarket/styles/main.css
  pandamarket/styles/signInUp.css
Labels: 매운맛🔥, 미완성🫠

#112 Part1 최태중 :: 스프린트 미션 2 구현 및 기존 미흡사항 보완.
  images/google_logo.png
  images/invisible.svg
  images/kakao_logo.png
  index.html
  login/index.html
  signup/index.html
  styles/index.css
  styles/member.css
Labels: 매운맛🔥

#115 [이영훈]sprint 1
  Img_home_01.png
  Img_home_02-1.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Property 1=Heart.png
  Property 1=Typo.png
  Property 1=Variant3.png
  Property 1=active.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  style.css
Labels: 매운맛🔥

#152 [김어진]sprint1
  image/Group 16.png
  image/Group.png
  image/Group3.png
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Vector.png
  image/ic_twitter.png
  index.html
  styles.css
Labels: 매운맛🔥, 순한맛🐑

#140 [이승현] sprint2
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  image/main-page/Img_home_01.png
  image/main-page/Img_home_02.png
  image/main-page/Img_home_03.png
  image/main-page/Img_home_bottom.png
  image/main-page/Img_home_top.png
  image/main-page/ic_facebook.png
  image/main-page/ic_instagram.png
  image/main-page/ic_twitter.png
  image/main-page/ic_youtube.png
  image/main-page/mainLogo.jpg
  image/main-page/판다마켓.jpg
  image/signin-page/Component 2@3x-1.png
  image/signin-page/Component 2@3x-2.png
  image/signin-page/Component 2@3x-3.png
  image/signin-page/Component 2@3x.png
  image/signin-page/Component 3@3x-1.png
  image/signin-page/Component 3@3x-2.png
  image/signin-page/Component 3@3x-3.png
  image/signin-page/Component 3@3x.png
  image/signin-page/Vector.png
  image/signin-page/Vectorx.png
  image/signin-page/btn_visibility_off_24px.png
  image/signin-page/btn_visibility_on_24px.png
  image/signin-page/logo@3x.png
  index.html
  login.html
  signup.html
  style.css
  style/common/_button.scss
  style/common/_container.scss
  style/common/_description.scss
  style/common/_link.scss
  style/content/_content.scss
  style/footer/_footer.scss
  style/header/_header.scss
  style/import/_import.scss
  style/main/_main.scss
  style/mixin/_mixin.scss
  style/style.css
  style/style.css.map
  style/style.scss
Labels: 매운맛🔥

#171 [김제완] sprint3
  css/style.css
  img/og-image.png
  index.html
  signin.html
Labels: 매운맛🔥

#153 [김지윤] Sprint3
  .prettierrc
  images/logo/og.png
  index.html
  signin.html
  signup.html
  styles/auth.css
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#159 [이송아] sprint3
  .github/pull_request_template.md
  images/og-tag.svg
  index.html
  js/include.js
  layout/footer.html
  layout/header.html
  pages/faq/index.html
  pages/items/index.html
  pages/login/index.html
  pages/privacy/index.html
  pages/signup/index.html
  pages/src/join-media.css
  pages/src/join.css
  styles/common.css
  styles/global.css
  styles/index.css
  styles/media.css
  styles/reset.css
Labels: 매운맛🔥

#198 [고한샘]Sprint3
  css/index.css
  css/login.css
  images/logo_home_word.svg
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#146 [정우기] Sprint3
  README.md
  assets/og-image.png
  index.html
  login.html
  login/style.css
  root.css
  signup.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#120 [이승헌] sprint 2
  assets/favicon.ico
  assets/ic_google.png
  assets/ic_invisible.png
  assets/ic_kakaotalk.png
  assets/ic_visible.png
  index.html
  login.html
  signin.html
  signup.html
  styles/common.css
  styles/home.css
  styles/sign.css
Labels: 매운맛🔥

#110 [오채연] sprint2
  css/signin.css
  css/signup.css
  faq.html
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic-eye.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_instagram.png
  img/ic_kakaotalk.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/img_logo.png
  img/login_logo.png
  img/판다 얼굴.png
  index.html
  items.html
  part1/signin.html
  privacy.html
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#158 [이율] Sprint 3
  pandaMarket/css/style.min.css
  pandaMarket/dist/img/logo.png
  pandaMarket/dist/scss/_index.scss
  pandaMarket/dist/scss/_layout.scss
  pandaMarket/img/Img_home_01.png
  pandaMarket/img/Img_home_02.png
  pandaMarket/img/Img_home_03.png
  pandaMarket/img/Img_home_bottom.png
  pandaMarket/img/Img_home_top.png
  pandaMarket/img/ic_facebook.svg
  pandaMarket/img/ic_google.svg
  pandaMarket/img/ic_instagram.svg
  pandaMarket/img/ic_kakao.svg
  pandaMarket/img/ic_twitter.svg
  pandaMarket/img/ic_visibility.svg
  pandaMarket/img/ic_youtube.svg
  pandaMarket/img/img_meta.png
  pandaMarket/img/logo-big.png
  pandaMarket/img/logo_img.png
  pandaMarket/img/logo_typo.png
  pandaMarket/img/spr.sprite.png
  pandaMarket/img/spr/visibility-off.png
  pandaMarket/img/spr/visibility-on.png
  pandaMarket/index.html
  pandaMarket/join.html
  pandaMarket/scss/_common.scss
  pandaMarket/scss/_component.scss
  pandaMarket/scss/_form.scss
  pandaMarket/scss/_index.scss
  pandaMarket/scss/_layout.scss
  pandaMarket/scss/_reset.scss
  pandaMarket/scss/_spr.scss
  pandaMarket/scss/_spr.sprite.scss
  pandaMarket/scss/spr.sprite
  pandaMarket/scss/style.scss
  pandaMarket/signin.html
Labels: 매운맛🔥

#211 [곽서연] sprint3
  .github/pull_request_template.md
  assets/google.png
  assets/kakaotalk.png
  assets/logo.png
  assets/panda-market-icon.png
  assets/visibility-off.png
  faq.html
  items.html
  login/login.css
  login/login.html
  main/footer-Panda.png
  main/ic-facebook.png
  main/ic-instagram.png
  main/ic-twitter.png
  main/ic-youtube.png
  main/index.html
  main/main.css
  policy.html
  signup/signup.css
  signup/signup.html
Labels: 매운맛🔥, 미완성🫠

#155 [이은빈] sprint3
  css/global.css
  css/style.css
  font/Abel-Regular.ttf
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/og_img.png
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#156 [천권희] Sprint3
  assets/icon/favicon.ico
  assets/img/preview_img.png
  docs/기능 목록.md
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/auth.css
  styles/main.css
  styles/variables.css
Labels: 매운맛🔥

#179 [채종민] sprint3
  code/css/main-media.css
  code/css/main.css
  code/css/signin.css
  code/pages/index.html
  code/pages/signin.html
  code/pages/signup.html
Labels: 매운맛🔥

#177 [이동석] sprint3
  images/logo/visibility-off.png
  images/social/facebook.png
  images/social/google.png
  images/social/instagram.png
  images/social/kakaotalk.png
  images/social/twitter.png
  images/social/youtube.png
  index.html
  signin.html
  signup.html
  style.css
  styles/common.css
  styles/signin.css
  styles/signup.css
  styles/style.css
Labels: 매운맛🔥
